In [1]:
import pandas as pd
import numpy as np
import glob
import re

## 芭樂交易量排行榜
根據交易資料統計，台中交易市場為最大，因此選擇以台中為主要分析資料，農測站選擇高雄農改

## 交易資料 => 使用台中市場

In [2]:
df_price = pd.read_csv("cleaned data/價格_全國芭樂交易資料(初步清洗).csv", usecols=[0, 1, 2, 3, 4, 5, 6, 7]) # 因稍候需要補差值，故略過百分比欄位
df_price.head()

           日期       市場          產品    上價    中價    下價  平均價(元/公斤)  交易量(公斤)
0  2011-01-01  104 台北二  P1 番石榴 珍珠芭  68.7  43.5  25.6       45.0    13878
1  2011-01-01  400 台中市  P1 番石榴 珍珠芭  49.3  33.2  19.6       33.7    18212
2  2011-01-01  600 嘉義市  P1 番石榴 珍珠芭  55.0  32.0  20.0       32.0     1440
3  2011-01-01  109 台北一  P1 番石榴 珍珠芭  69.5  40.9  24.8       43.4    34632
4  2011-01-01  800 高雄市  P1 番石榴 珍珠芭  37.6  27.4  20.0       28.0      518

In [3]:
## 只留下三重市場資料
df_price_Sanchong = df_price.loc[df_price["市場"] == "241 三重區"]

In [4]:
df_price_Sanchong["日期"] = pd.to_datetime(df_price_Sanchong["日期"])
df_price_Sanchong.set_index("日期", inplace=True)

<ipython-input-4-65687477ee06>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_price_Sanchong["日期"] = pd.to_datetime(df_price_Sanchong["日期"])

In [5]:
df_price_Sanchong

                 市場          產品    上價    中價    下價  平均價(元/公斤)  交易量(公斤)
日期
2011-01-01  241 三重區  P1 番石榴 珍珠芭  54.9  34.9  30.2       37.9    34495
2011-01-02  241 三重區  P1 番石榴 珍珠芭  56.8  35.9  30.3       38.9    24739
2011-01-04  241 三重區  P1 番石榴 珍珠芭  61.5  35.4  28.1       39.1    24677
2011-01-05  241 三重區  P1 番石榴 珍珠芭  61.7  35.9  28.6       39.6    23480
2011-01-06  241 三重區  P1 番石榴 珍珠芭  61.5  37.2  28.8       40.4    23758
...             ...         ...   ...   ...   ...        ...      ...
2021-07-03  241 三重區  P1 番石榴 珍珠芭  39.1  23.6  19.8       26.0    40627
2021-07-04  241 三重區  P1 番石榴 珍珠芭  41.4  25.4  19.8       27.5    36127
2021-07-06  241 三重區  P1 番石榴 珍珠芭  43.0  24.6  18.8       27.1    36871
2021-07-07  241 三重區  P1 番石榴 珍珠芭  43.7  23.5  19.9       26.8    35240
2021-07-08  241 三重區  P1 番石榴 珍珠芭  43.7  25.3  20.7       28.1    33006

[3164 rows x 7 columns]

In [6]:
df_price_Sanchong.dtypes

市場            object
產品            object
上價           float64
中價           float64
下價           float64
平均價(元/公斤)    float64
交易量(公斤)        int64
dtype: object

### 補上週末六日(是否需要補，尚待討論＆結果觀察)
- 目前使用ffill（補前值），這方法不太好，雖補齊休假日空缺，但是否影響資料整體尚待評估 => 使用resample("D")，以日為單位重採集資料
- 重算百分比變化 => 使用**shift()**
- 交易量變動量大原因 => 星期一、逢年過節?

In [7]:
df_price_Sanchong = df_price_Sanchong.resample("D").ffill()
df_price_Sanchong

                 市場          產品    上價    中價    下價  平均價(元/公斤)  交易量(公斤)
日期
2011-01-01  241 三重區  P1 番石榴 珍珠芭  54.9  34.9  30.2       37.9    34495
2011-01-02  241 三重區  P1 番石榴 珍珠芭  56.8  35.9  30.3       38.9    24739
2011-01-03  241 三重區  P1 番石榴 珍珠芭  56.8  35.9  30.3       38.9    24739
2011-01-04  241 三重區  P1 番石榴 珍珠芭  61.5  35.4  28.1       39.1    24677
2011-01-05  241 三重區  P1 番石榴 珍珠芭  61.7  35.9  28.6       39.6    23480
...             ...         ...   ...   ...   ...        ...      ...
2021-07-04  241 三重區  P1 番石榴 珍珠芭  41.4  25.4  19.8       27.5    36127
2021-07-05  241 三重區  P1 番石榴 珍珠芭  41.4  25.4  19.8       27.5    36127
2021-07-06  241 三重區  P1 番石榴 珍珠芭  43.0  24.6  18.8       27.1    36871
2021-07-07  241 三重區  P1 番石榴 珍珠芭  43.7  23.5  19.9       26.8    35240
2021-07-08  241 三重區  P1 番石榴 珍珠芭  43.7  25.3  20.7       28.1    33006

[3842 rows x 7 columns]

## 天氣資料 => 使用日月潭測站資料

### 異常值符號代表意義&處理方式

In [8]:
dict_symbol = {"Symbol":["T", "x", "&", "V", "/", "..."],
               "Explanation":["微量(小於 0.1mm)", "故障", "降水量資料累積於後", "風向不定", "不明", "無觀測"],
               "Replacement":[0.0, "ffill", "ffill", "ffill", "ffill", "ffill"]
              }
df_symbol = pd.DataFrame(dict_symbol)
df_symbol

  Symbol   Explanation Replacement
0      T  微量(小於 0.1mm)           0
1      x            故障       ffill
2      &     降水量資料累積於後       ffill
3      V          風向不定       ffill
4      /            不明       ffill
5    ...           無觀測       ffill

### 中英欄位對照表

In [9]:
col_data = "觀測時間(LST)ObsTime、測站氣壓(hPa)StnPres、海平面氣壓(hPa)SeaPres、測站最高氣壓(hPa)StnPresMax、測站最高氣壓時間(LST)StnPresMaxTime、測站最低氣壓(hPa)StnPresMin、測站最低氣壓時間(LST)StnPresMinTime、氣溫(℃)Temperature、最高氣溫(℃)T Max、最高氣溫時間(LST)T Max Time、最低氣溫(℃)T Min、最低氣溫時間(LST)T Min Time、露點溫度(℃)Td dew point、相對溼度(%)RH、最小相對溼度(%)RHMin、最小相對溼度時間(LST)RHMinTime、風速(m/s)WS、風向(360degree)WD、最大陣風(m/s)WSGust、最大陣風風向(360degree)WDGust、最大陣風風速時間(LST)WGustTime、降水量(mm)Precp、降水時數(hr)PrecpHour、10分鐘最大降水量(mm)PrecpMax10、10分鐘最大降水起始時間(LST)PrecpMax10Time、一小時最大降水量(mm)PrecpHrMax、一小時最大降水量起始時間(LST)PrecpHrMaxTime、日照時數(hr)SunShine、日照率(%)SunShineRate、全天空日射量(MJ/㎡)GloblRad、能見度(km)VisbMean、A型蒸發量(mm)EvapA"
datas = [i for i in col_data.split("、")]
chi,eng =[],[]
for data in datas:
    chi.append(data.split(")")[0]+")")
    eng.append(data.split(")")[1])
df_columns_name = pd.DataFrame({"英文名稱":eng, 
                                "中文名稱":chi})
df_columns_name

              英文名稱               中文名稱
0          ObsTime          觀測時間(LST)
1          StnPres          測站氣壓(hPa)
2          SeaPres         海平面氣壓(hPa)
3       StnPresMax        測站最高氣壓(hPa)
4   StnPresMaxTime      測站最高氣壓時間(LST)
5       StnPresMin        測站最低氣壓(hPa)
6   StnPresMinTime      測站最低氣壓時間(LST)
7      Temperature              氣溫(℃)
8            T Max            最高氣溫(℃)
9       T Max Time        最高氣溫時間(LST)
10           T Min            最低氣溫(℃)
11      T Min Time        最低氣溫時間(LST)
12    Td dew point            露點溫度(℃)
13              RH            相對溼度(%)
14           RHMin          最小相對溼度(%)
15       RHMinTime      最小相對溼度時間(LST)
16              WS            風速(m/s)
17              WD      風向(360degree)
18          WSGust          最大陣風(m/s)
19          WDGust  最大陣風風向(360degree)
20       WGustTime      最大陣風風速時間(LST)
21           Precp            降水量(mm)
22       PrecpHour           降水時數(hr)
23      PrecpMax10      10分鐘最大降水量(mm)
24  PrecpMax10Time  10分鐘最大降水起始時間(LST)
25      PrecpHrMax       一小時最大降水量(mm)
26  PrecpHrMaxTime  一小時最大降水量起始時間(LST)
27        SunShine           日照時數(hr)
28    SunShineRate             日照率(%)
29        GloblRad       全天空日射量(MJ/㎡)
30        VisbMean            能見度(km)
31           EvapA          A型蒸發量(mm)

In [10]:
# concat 2011~ 2021的資料，選擇欲使用之欄位
cols = ['日期', '平均地溫100cm(℃)',  '平均氣溫(℃)', '平均氣壓(hPa)', '平均相對溼度( %)','累積日射量(MJm2)','累積日照時數(hr)', '累計雨量(mm)']

df_weather = ""
for csv in glob.glob(r"cleaned data/Agricultural_Weather_Datas(merged)/高雄農改/*.csv"):
    if csv == r"cleaned data/Agricultural_Weather_Datas(merged)/高雄農改\2011_高雄農改.csv":
        df_weather = pd.read_csv(r"cleaned data/Agricultural_Weather_Datas(merged)/高雄農改\2011_高雄農改.csv", usecols=cols)
        continue
    df = pd.read_csv(csv, usecols=cols)
    df_weather = pd.concat([df_weather, df], sort=False)
    
df_weather

,日期,平均地溫100cm(℃),平均氣壓(hPa),平均氣溫(℃),平均相對溼度( %),累積日射量(MJm2),累積日照時數(hr),累計雨量(mm)
0,2011-01-01,24.1,1013.1,16.0,66.0,6.21,3.8,0.0
1,2011-01-02,24.0,1014.6,17.1,73.0,8.90,7.3,0.0
2,2011-01-03,23.9,1013.5,17.2,78.0,8.23,6.4,0.0
3,2011-01-04,23.8,1013.7,17.5,76.0,9.19,8.3,0.0
4,2011-01-05,23.7,1012.7,18.6,78.0,6.00,4.1,0.0
...,...,...,...,...,...,...,...,...
360,2021-12-27,0.0,0.0,0.0,0.0,0.00,0.0,0.0
361,2021-12-28,0.0,0.0,0.0,0.0,0.00,0.0,0.0
362,2021-12-29,0.0,0.0,0.0,0.0,0.00,0.0,0.0
363,2021-12-30,0.0,0.0,0.0,0.0,0.00,0.0,0.0
364,2021-12-31,0.0,0.0,0.0,0.0,0.00,0.0,0.0

In [11]:
df_weather["日期"] = df_weather["日期"].apply(lambda x: pd.Timestamp(x))
df_weather = df_weather[df_weather["日期"] < pd.Timestamp("2021-06-15")]
df_weather["日期"] = pd.to_datetime(df_weather["日期"])

<ipython-input-11-e2853b0a8fdd>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_weather["日期"] = pd.to_datetime(df_weather["日期"])

In [12]:
df_weather.head()

,日期,平均地溫100cm(℃),平均氣壓(hPa),平均氣溫(℃),平均相對溼度( %),累積日射量(MJm2),累積日照時數(hr),累計雨量(mm)
0,2011-01-01,24.1,1013.1,16.0,66.0,6.21,3.8,0.0
1,2011-01-02,24.0,1014.6,17.1,73.0,8.90,7.3,0.0
2,2011-01-03,23.9,1013.5,17.2,78.0,8.23,6.4,0.0
3,2011-01-04,23.8,1013.7,17.5,76.0,9.19,8.3,0.0
4,2011-01-05,23.7,1012.7,18.6,78.0,6.00,4.1,0.0

In [13]:
df_price_Sanchong.head()

                 市場          產品    上價    中價    下價  平均價(元/公斤)  交易量(公斤)
日期
2011-01-01  241 三重區  P1 番石榴 珍珠芭  54.9  34.9  30.2       37.9    34495
2011-01-02  241 三重區  P1 番石榴 珍珠芭  56.8  35.9  30.3       38.9    24739
2011-01-03  241 三重區  P1 番石榴 珍珠芭  56.8  35.9  30.3       38.9    24739
2011-01-04  241 三重區  P1 番石榴 珍珠芭  61.5  35.4  28.1       39.1    24677
2011-01-05  241 三重區  P1 番石榴 珍珠芭  61.7  35.9  28.6       39.6    23480

### 合併dataframe

In [14]:
df_merged = df_price_Sanchong.merge(df_weather, how="left", on="日期").drop(columns=['市場', '上價', '中價', '下價'])
df_merged

,日期,產品,平均價(元/公斤),交易量(公斤),平均地溫100cm(℃),平均氣壓(hPa),平均氣溫(℃),平均相對溼度( %),累積日射量(MJm2),累積日照時數(hr),累計雨量(mm)
0,2011-01-01,P1 番石榴 珍珠芭,37.9,34495,24.1,1013.1,16.0,66.0,6.21,3.8,0.0
1,2011-01-02,P1 番石榴 珍珠芭,38.9,24739,24.0,1014.6,17.1,73.0,8.90,7.3,0.0
2,2011-01-03,P1 番石榴 珍珠芭,38.9,24739,23.9,1013.5,17.2,78.0,8.23,6.4,0.0
3,2011-01-04,P1 番石榴 珍珠芭,39.1,24677,23.8,1013.7,17.5,76.0,9.19,8.3,0.0
4,2011-01-05,P1 番石榴 珍珠芭,39.6,23480,23.7,1012.7,18.6,78.0,6.00,4.1,0.0
...,...,...,...,...,...,...,...,...,...,...,...
3837,2021-07-04,P1 番石榴 珍珠芭,27.5,36127,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3838,2021-07-05,P1 番石榴 珍珠芭,27.5,36127,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3839,2021-07-06,P1 番石榴 珍珠芭,27.1,36871,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3840,2021-07-07,P1 番石榴 珍珠芭,26.8,35240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3841,2021-07-08,P1 番石榴 珍珠芭,28.1,33006,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 新增欄位(五日均溫)

In [15]:
df_merged["5日平均地溫100cm(℃)"] = df_merged["平均地溫100cm(℃)"].shift(5)
df_merged["5日平均累積日照時數(hr)"] = df_merged["累積日照時數(hr)"].shift(5)
df_merged["3日累計雨量(mm)"] = df_merged["累計雨量(mm)"].shift(3)

In [16]:
df_test = df_merged.dropna(how="any")
df_test.head()

,日期,產品,平均價(元/公斤),交易量(公斤),平均地溫100cm(℃),平均氣壓(hPa),平均氣溫(℃),平均相對溼度( %),累積日射量(MJm2),累積日照時數(hr),累計雨量(mm),5日平均地溫100cm(℃),5日平均累積日照時數(hr),3日累計雨量(mm)
5,2011-01-06,P1 番石榴 珍珠芭,40.4,23758,23.7,1013.3,18.5,85.0,4.05,0.0,0.5,24.1,3.8,0.0
6,2011-01-07,P1 番石榴 珍珠芭,36.6,28553,23.6,1015.5,14.8,82.0,2.46,0.0,0.0,24.0,7.3,0.0
7,2011-01-08,P1 番石榴 珍珠芭,36.9,37217,23.5,1013.4,17.9,78.0,8.11,7.3,0.0,23.9,6.4,0.0
8,2011-01-09,P1 番石榴 珍珠芭,34.8,41087,23.5,1011.7,19.6,77.0,7.43,5.9,0.0,23.8,8.3,0.5
9,2011-01-10,P1 番石榴 珍珠芭,34.8,41087,23.4,1011.8,17.6,77.0,5.39,2.1,0.0,23.7,4.1,0.0

### 輸出為csv檔

In [18]:
df_test.to_csv("analysis data/芭樂分析資料(交易&天氣).csv", index=False)